version: '3.4'

services:
  demostrativo.ocelot.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      # - "443"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  demostrativo.hv.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5010:80"
    #   - "443"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  demostrativo.jwt.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5020:80"
    #   - "443"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
